services:
  web1:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web1
    ports:
    - "80:80"
    networks:
      - asa-network

networks:
  asa-network:
    driver: bridge

 #  servidor2:
 #    build: 
 #      context: ./server2
 #      dockerfile: Dockerfile
 #    container_name: server2
 #    networks:
 #      - asa-network